"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-13 20:41:25.265200
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Needed for the outreach EXCLUDE constraint (integer equality inside a GiST index).
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "curators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spotify_user_id", sa.String(length=100), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("excluded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exclusion_reason", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "exclusion_reason in ('bad-fit', 'dead')", name=op.f("ck_curators_exclusion_reason")
        ),
        sa.CheckConstraint(
            "(excluded_at is null) = (exclusion_reason is null)", name=op.f("ck_curators_exclusion_complete")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_curators")),
        sa.UniqueConstraint("spotify_user_id", name=op.f("uq_curators_spotify_user_id")),
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("digest_target", sa.Integer(), server_default="20", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("digest_target between 1 and 50", name=op.f("ck_profiles_digest_target")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profiles")),
        sa.UniqueConstraint("name", name=op.f("uq_profiles_name")),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="running", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "heartbeat_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("search_calls", sa.Integer(), server_default="0", nullable=False),
        sa.Column("llm_spend_usd", sa.Numeric(precision=10, scale=4), server_default="0", nullable=False),
        sa.CheckConstraint("status in ('running', 'succeeded', 'failed')", name=op.f("ck_runs_status")),
        sa.CheckConstraint("trigger in ('schedule', 'manual')", name=op.f("ck_runs_trigger")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_table(
        "anti_signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=False),
        sa.Column("normalized_value", sa.String(length=200), nullable=False),
        sa.CheckConstraint("kind in ('artist', 'term')", name=op.f("ck_anti_signals_kind")),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_anti_signals_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anti_signals")),
        sa.UniqueConstraint(
            "profile_id",
            "kind",
            "normalized_value",
            name=op.f("uq_anti_signals_profile_id_kind_normalized_value"),
        ),
    )
    op.create_table(
        "playlists",
        sa.Column("spotify_id", sa.String(length=22), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_spotify_id", sa.String(length=100), nullable=True),
        sa.Column("owner_name", sa.String(length=200), nullable=True),
        sa.Column("curator_id", sa.Integer(), nullable=True),
        sa.Column("followers", sa.Integer(), nullable=True),
        sa.Column("track_count", sa.Integer(), nullable=True),
        sa.Column("last_add_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("size_band", sa.String(length=20), nullable=True),
        sa.Column("is_alive", sa.Boolean(), nullable=True),
        sa.Column("is_real", sa.Boolean(), nullable=True),
        sa.Column("reachability", sa.String(length=20), nullable=True),
        sa.Column("cover_image_url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="candidate", nullable=False),
        sa.Column("rejection_reason", sa.String(length=20), nullable=True),
        sa.Column(
            "first_seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'rejected') = (rejection_reason is not null)",
            name=op.f("ck_playlists_rejection_has_reason"),
        ),
        sa.CheckConstraint(
            "reachability in ('curator', 'spotify', 'label', 'distributor')",
            name=op.f("ck_playlists_reachability"),
        ),
        sa.CheckConstraint(
            "rejection_reason in ('not-alive', 'not-real', 'no-fit')",
            name=op.f("ck_playlists_rejection_reason"),
        ),
        sa.CheckConstraint(
            "size_band in ('under-500', '500-2k', '2k-10k', '10k-plus')", name=op.f("ck_playlists_size_band")
        ),
        sa.CheckConstraint(
            "status in ('candidate', 'qualified', 'rejected', 'no-contact', 'digested', 'fetch-failed')",
            name=op.f("ck_playlists_status"),
        ),
        sa.ForeignKeyConstraint(
            ["curator_id"],
            ["curators.id"],
            name=op.f("fk_playlists_curator_id_curators"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("spotify_id", name=op.f("pk_playlists")),
    )
    op.create_table(
        "profile_genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(length=100), nullable=False),
        sa.Column("normalized_tag", sa.String(length=100), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_profile_genres_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_genres")),
        sa.UniqueConstraint(
            "profile_id", "normalized_tag", name=op.f("uq_profile_genres_profile_id_normalized_tag")
        ),
    )
    op.create_table(
        "profile_tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("spotify_url", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=300), server_default="", nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_profile_tracks_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_tracks")),
        sa.UniqueConstraint(
            "profile_id", "spotify_url", name=op.f("uq_profile_tracks_profile_id_spotify_url")
        ),
    )
    op.create_table(
        "reference_artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("spotify_artist_id", sa.String(length=22), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_reference_artists_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_artists")),
        sa.UniqueConstraint(
            "profile_id", "normalized_name", name=op.f("uq_reference_artists_profile_id_normalized_name")
        ),
    )
    op.create_table(
        "run_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "requested_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("requested_by", sa.String(length=320), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status in ('pending', 'claimed', 'done', 'failed')", name=op.f("ck_run_requests_status")
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_run_requests_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_requests")),
    )
    op.create_table(
        "run_stage_counts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("count_in", sa.Integer(), server_default="0", nullable=False),
        sa.Column("count_out", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_run_stage_counts_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_stage_counts_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_stage_counts")),
    )
    op.create_table(
        "search_terms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("term", sa.String(length=200), nullable=False),
        sa.Column("normalized_term", sa.String(length=200), nullable=False),
        sa.Column("origin", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("origin in ('manual', 'suggested')", name=op.f("ck_search_terms_origin")),
        sa.CheckConstraint(
            "status in ('proposed', 'active', 'paused', 'rejected')", name=op.f("ck_search_terms_status")
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_search_terms_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_terms")),
        sa.UniqueConstraint(
            "profile_id", "normalized_term", name=op.f("uq_search_terms_profile_id_normalized_term")
        ),
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("curator_id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.String(length=22), nullable=True),
        sa.Column("route_type", sa.String(length=20), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("contact_key", sa.String(length=400), nullable=False),
        sa.Column("domain_key", sa.String(length=300), nullable=True),
        sa.Column("confidence", sa.String(length=1), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("confidence in ('A', 'B', 'C')", name=op.f("ck_contacts_confidence")),
        sa.CheckConstraint(
            "route_type in ('email', 'submission-form', 'instagram', 'x', 'bluesky', 'other')",
            name=op.f("ck_contacts_route_type"),
        ),
        sa.ForeignKeyConstraint(
            ["curator_id"], ["curators.id"], name=op.f("fk_contacts_curator_id_curators"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.spotify_id"],
            name=op.f("fk_contacts_playlist_id_playlists"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
        sa.UniqueConstraint("contact_key", name=op.f("uq_contacts_contact_key")),
    )
    op.create_index(op.f("ix_contacts_domain_key"), "contacts", ["domain_key"], unique=False)
    op.create_table(
        "outreach",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("curator_id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.String(length=22), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("digest_date", sa.Date(), nullable=False),
        sa.Column("brief_text", sa.Text(), nullable=False),
        sa.Column("suggested_angle", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="new", nullable=False),
        sa.Column("pitched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status in ('new', 'pitched', 'skip', 'bad-fit', 'dead', 'replied', 'placed')",
            name=op.f("ck_outreach_status"),
        ),
        sa.ForeignKeyConstraint(
            ["curator_id"], ["curators.id"], name=op.f("fk_outreach_curator_id_curators"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.spotify_id"],
            name=op.f("fk_outreach_playlist_id_playlists"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["profiles.id"], name=op.f("fk_outreach_profile_id_profiles"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach")),
    )
    op.create_table(
        "playlist_profile_fit",
        sa.Column("playlist_id", sa.String(length=22), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("fit_score", sa.Float(), nullable=False),
        sa.Column(
            "reference_artists_present", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False
        ),
        sa.Column("genre_tags", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("qualified", sa.Boolean(), nullable=False),
        sa.Column("scored_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.spotify_id"],
            name=op.f("fk_playlist_profile_fit_playlist_id_playlists"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_playlist_profile_fit_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("playlist_id", "profile_id", name=op.f("pk_playlist_profile_fit")),
    )
    op.create_table(
        "playlist_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.String(length=22), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("search_term_id", sa.Integer(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("found_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "provider in ('serper', 'brave', 'neighbour')", name=op.f("ck_playlist_sources_provider")
        ),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.spotify_id"],
            name=op.f("fk_playlist_sources_playlist_id_playlists"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_playlist_sources_run_id_runs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["search_term_id"],
            ["search_terms.id"],
            name=op.f("fk_playlist_sources_search_term_id_search_terms"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playlist_sources")),
    )
    # ### end Alembic commands ###

    # --- Hand-written guarantees (not expressible in the models) ---------------------------

    # A curator appears in at most one digest entry per 90 days, across every profile.
    # [digest_date, digest_date + 90) ranges may not overlap for the same curator, so a
    # second entry is allowed from day 90 onwards. 90 is written literally on purpose:
    # migrations are frozen history, even if core.exclusion.COOLDOWN_DAYS changes later.
    op.execute(
        """
        ALTER TABLE outreach ADD CONSTRAINT ex_outreach_curator_cooldown
        EXCLUDE USING gist (curator_id WITH =, daterange(digest_date, digest_date + 90) WITH &&)
        """
    )

    # A playlist is recorded once per run, provider and search term (NULL run/term included).
    op.execute(
        """
        CREATE UNIQUE INDEX uq_playlist_sources_origin
        ON playlist_sources (playlist_id, run_id, provider, search_term_id) NULLS NOT DISTINCT
        """
    )

    # One count row per run, profile (NULL = all profiles) and stage.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_run_stage_counts_run_profile_stage
        ON run_stage_counts (run_id, profile_id, stage) NULLS NOT DISTINCT
        """
    )

    # Only one open "Run now" per scope (NULL profile = everything); repeat clicks do nothing.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_run_requests_one_open_per_scope
        ON run_requests (profile_id) NULLS NOT DISTINCT
        WHERE status IN ('pending', 'claimed')
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playlist_sources")
    op.drop_table("playlist_profile_fit")
    op.drop_table("outreach")
    op.drop_index(op.f("ix_contacts_domain_key"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_table("search_terms")
    op.drop_table("run_stage_counts")
    op.drop_table("run_requests")
    op.drop_table("reference_artists")
    op.drop_table("profile_tracks")
    op.drop_table("profile_genres")
    op.drop_table("playlists")
    op.drop_table("anti_signals")
    op.drop_table("runs")
    op.drop_table("profiles")
    op.drop_table("curators")
    # ### end Alembic commands ###
